name: Assemble

on:
    pull_request:
        branches: [ master, stable-* ]
    push:
        branches: [ master, stable-* ]

jobs:
    assemble:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
            - name: Set up JDK 17
              uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93 # v4.0.0
              with:
                  distribution: "temurin"
                  java-version: 17
            -   name: Setup JVM options
                run: |
                    mkdir -p "$HOME/.gradle"
                    echo "org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError" > "$HOME/.gradle/gradle.properties"
            -   name: Assemble
                uses: gradle/gradle-build-action@v2
                with:
                    arguments: assemble
